language: php
dist: bionic # https://docs.travis-ci.com/user/reference/overview/#which-one-do-i-use

stages:
  - smoke test 🕵️
  - test

jobs:
  include:
    - stage: smoke test 🕵️
      php: 7.3
      env: DEPS='lowest'
    -
      php: 8.0
      env: DEPS='unmodified'

    - stage: test
      php: 7.4
      env: SYMFONY_VERSION='3.4.*'
    # TODO remove as soon as Symfony >= 4.2 is required
    -
      php: 7.4
      env: SYMFONY_VERSION='3.4.*' WITH_TRANSLATION_CONTRACTS='yes'
    -
      php: 7.4
      env: SYMFONY_VERSION='4.4.*'
  fast_finish: true

install:
  # set unlimited memory_limit
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "memory_limit = -1" >> "${INI_FILE}"
  # disable Xdebug for better Composer performance
  - if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi;
  # install dependencies using Composer
  - travis_wait bash .travis_install_dependencies.sh
  # show installed dependencies
  - composer show

before_script:
  # create folder for code coverage data
  - mkdir -p build/logs
  # install PCOV extension for quick code coverage analysis
  - pecl install pcov
script:
  # validate composer.json
  - composer validate --strict --no-check-lock
  # run PHPUnit
  - php vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml
  # upload code coverage data
  - |
    if [ "${TRAVIS_REPO_SLUG}" = "craue/CraueFormFlowDemoBundle" ]; then
      PHP_COVERALLS_VERSION=`curl --retry 5 -Is https://github.com/php-coveralls/php-coveralls/releases/latest | grep -i 'Location:' | sed 's/.*\/tag\/\(.*\)$/\1/' | tr -d "[:cntrl:]"`
      echo "using php-coveralls '${PHP_COVERALLS_VERSION}'"
      travis_retry wget -q "https://github.com/php-coveralls/php-coveralls/releases/download/${PHP_COVERALLS_VERSION}/php-coveralls.phar" -O php-coveralls.phar
      travis_retry php php-coveralls.phar -v
    fi

notifications:
  email:
    on_success: always
    on_failure: always

# cache Composer's package cache
cache:
  directories:
    - $HOME/.composer/cache/files
